# Lamdeni
[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/ai-assistant"
  to = "/.netlify/functions/ai-assistant"
  status = 200

[[redirects]]
  from = "/api/send-push"
  to = "/.netlify/functions/send-push"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
